version: "3.8"
services:
  app1:
    restart: always
    build: ./Server
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5001:5000"
    volumes:
      - .:/code
    expose:
      - "5001"
    mem_limit: 1GB
    mem_reservation: 128M
    cpus: 0.125
  app2:
    restart: always
    build: ./Server
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5002:5000"
    volumes:
      - .:/code
    expose:
      - "5002"
    mem_limit: 1GB
    mem_reservation: 128M
    cpus: 0.125
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - /data
