version: "3.8"
services:
  web:
    restart: always
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    expose:
      - "5000"
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5
